<?php
namespace CGM\FinancialNews\Core\Admin;

/**
 * Handles WordPress Admin Menu Pages and enqueues JS/CSS assets.
 */
class AdminController {

	private const MENU_SLUG = 'cgm-financial-news';

	/**
	 * Register hooks.
	 */
	public function hooks() {
		add_action( 'admin_menu', [ $this, 'register_admin_pages' ] );
		add_action( 'admin_enqueue_scripts', [ $this, 'enqueue_admin_assets' ] );
	}

	/**
	 * Register the plugin admin menu pages.
	 */
	public function register_admin_pages() {
		// Register Parent Menu
		add_menu_page(
			__( 'Financial News', 'cgm-financial-news' ),
			__( 'Financial News', 'cgm-financial-news' ),
			'manage_options',
			self::MENU_SLUG,
			[ $this, 'render_admin_page' ],
			'dashicons-chart-line',
			30
		);
	}

	/**
	 * Render the React app container placeholder.
	 */
	public function render_admin_page() {
		?>
		<div class="wrap">
			<div id="cgm-financial-news-admin-app">
				<div class="cgm-loading-spinner" style="padding: 40px; text-align: center; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
					<h2><?php esc_html_e( 'Loading CGM Financial News Panel...', 'cgm-financial-news' ); ?></h2>
					<p style="color: #64748b;"><?php esc_html_e( 'Please wait while the dashboard initializes.', 'cgm-financial-news' ); ?></p>
				</div>
			</div>
		</div>
		<?php
	}

	/**
	 * Enqueue compiled React JS and CSS.
	 *
	 * @param string $hook_suffix
	 */
	public function enqueue_admin_assets( $hook_suffix ) {
		// Only enqueue on our specific plugin admin menu page.
		if ( 'toplevel_page_' . self::MENU_SLUG !== $hook_suffix ) {
			return;
		}

		$asset_file = CGM_FN_PATH . 'build/index.asset.php';
		$dependencies = [ 'wp-element', 'wp-api-fetch' ];
		$version      = CGM_FN_VERSION;

		// If wp-scripts build file exists, use its autogenerated dependencies and version
		if ( file_exists( $asset_file ) ) {
			$assets       = require $asset_file;
			$dependencies = $assets['dependencies'] ?? $dependencies;
			$version      = $assets['version'] ?? $version;
		}

		// Enqueue Ant Design standard variables if required or compile inside JS.
		// Since we bundle Antd in the webpack bundle (index.js), it is self-contained.
		// Enqueue React Script
		wp_enqueue_script(
			'cgm-news-admin-js',
			plugins_url( 'build/index.js', CGM_FN_FILE ),
			$dependencies,
			$version,
			true
		);

		// Enqueue React CSS
		if ( file_exists( CGM_FN_PATH . 'build/index.css' ) ) {
			wp_enqueue_style(
				'cgm-news-admin-css',
				plugins_url( 'build/index.css', CGM_FN_FILE ),
				[],
				$version
			);
		}

		// Localize parameters for the React application
		wp_localize_script(
			'cgm-news-admin-js',
			'cgmAdminData',
			[
				'root'      => esc_url_raw( rest_url() ),
				'namespace' => 'cgm-financial-news/v1',
				'nonce'     => wp_create_nonce( 'wp_rest' ),
				'siteUrl'   => esc_url( site_url() ),
				'postType'  => 'post',
				'cptListUrl' => esc_url( admin_url( 'edit.php' ) ),
			]
		);
	}
}
